"""empty message

Revision ID: 655dcd948595
Revises: b19c01fce7c3
Create Date: 2020-07-19 10:13:07.669399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '655dcd948595'
down_revision = 'b19c01fce7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
